language: ru

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 2
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "bert-base-cased"
  cache_dir: null
- name: DIETClassifier
  epochs: 100
  transformer_size: 128
  number_of_transformer_layers: 2
  use_masked_language_model: false
  batch_strategy: "balanced"
  hidden_layers_sizes:
    text: [32]
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100

policies:
- name: MemoizationPolicy
  max_history: 2
- name: RulePolicy
- name: TEDPolicy
  epochs: 100
  constrain_similarities: true
assistant_id: 20250606-233502-relative-castle
